### ISSUE TITLE
Unable to mount developer image.

### ISSUE THREAD

**Issue by gyCfjSnO** [master131/iFakeLocation#1]
Unable to mount developer image.

System Version:	macOS 10.14.4 (18E226)
Kernel Version:	Darwin 18.5.0

**Comment by master131** [comment]
What iOS version is the device you are trying to use?

**Comment by carlenet** [comment]
I'm getting the same error iOS 12.2

**Comment by master131** [comment]
Unfortunately without active access to a Mac environment this may take some time for me to debug.
