### ISSUE TITLE
Your device's iOS version is not supported at this time.

### ISSUE THREAD

**Issue by igorzhvelmie** [master131/iFakeLocation#10]
Your device's iOS version is not supported at this time.
Version IOS 13.3

**Comment by bgktmxg** [comment]
Make a copy of the 13.2 folder inside developer images and rename it to 13.3. It will work straight away

**Comment by igorzhvelmie** [comment]
Thanks for answer @bgktmxg, I got 'Unable to mount developer image.' with 13.3 folder name. As I understand need a new developer image for IOS 13.3 (17C54)?
