### ISSUE TITLE
Not working on MacOS Ventura Public Beta 6

### ISSUE THREAD

**Issue by dionfactor** [master131/iFakeLocation#100]
Not expecting this to work on Beta versions of Operating Systems but just flagging that setting a location doesn't appear to work on MacOS Ventura Public Beta 6. When setting a location, the button goes grey and nothing appears to happen, and location doesn't actually update to phone. Screenshot below:

<img width="994" alt="Screenshot 2022-09-27 at 8 29 14 am" src="https://user-images.githubusercontent.com/16534472/192392118-8bb22a6a-6e00-41ab-9899-70cb12f583f2.png">

**Comment by master131** [comment]
Can you open the Terminal and run these commands (this assumes you have placed the iFakeLocation app on your desktop, change the location if required):

```
cd ~/Desktop/iFakeLocation.app
./iFakeLocation
```

Then try to set the location in the browser when it pops up and then check the Terminal app for any errors and share the details here.

**Comment by dionfactor** [comment]
Amazing, opening the app using Terminal fixed the issue!

**Comment by master131** [comment]
Oh, I wasn't expecting that to fix the issue... 😆
