### ISSUE TITLE
Having an error after ios upgrade.

### ISSUE THREAD

**Issue by artxty2** [master131/iFakeLocation#101]
Hi Master131,

i got this error:
Mount failed with status: N/A and error: ImageMountFailed

recent update on iphone ios16.0.2
using macos monterey v12.5.1

i tried restarting both the phone and mac.
i tried rebooting the iphone, it is detected but still getting the error above.

the ifakelocation works in locating in the map, but wont work when i clicked on the Set Fake Location.

btw, i confirm that the ifakelocation is working with the ipad ios 15.7, i think its because of the new ios16.0.2.

Thanks

**Comment by master131** [comment]
Can you confirm that you are using iFakeLocation v1.7.0?

**Comment by artxty2** [comment]
i was able to run the ifakelocation.app
but got this error:
Please turn on Developer Mode first via Setings >> Privacy & Security.

please advise.

**Comment by master131** [comment]
Do exactly as asked; go on your iPhone and tap Settings >> Privacy & Security and scroll down to Developer Mode and turn it on.

![image](https://user-images.githubusercontent.com/1592009/192520059-c4145499-0111-459b-bc46-f2b99a03d06e.png)

**Comment by artxty2** [comment]
Thank you, it worked. my bad i was going through the privacy setting on the mac and i just realiased it should have been on the iphone.
Thank you again, i really appreciate your help.
