### ISSUE TITLE
Unable to mount developer image...

### ISSUE THREAD

**Issue by kimmmchung** [master131/iFakeLocation#11]
Hi master131, I've been using your iFakeLoc for a few months and really enjoying it. I however updated my phone to iOS 13.3 and since then the iFakelocation wouldn't work :( It kept saying "iOS not supported" so I tried to look for solutions and found one that said to change the developer image folder name to the iOS version, which I did, named it "13.3". However still not working, now the error message is "Unable to mount developer image." 
![Capture2](https://user-images.githubusercontent.com/60998501/74402551-8ba61b00-4e5f-11ea-8719-7d0e00e606c5.PNG)
![Capture](https://user-images.githubusercontent.com/60998501/74402553-8d6fde80-4e5f-11ea-9011-207ac6af800f.PNG)

Thank you so much in advanced for your help!

**Comment by bgktmxg** [comment]
Whenever ive had these little issues ive just tried unplugging and plugging back in and trying again. Make sure theres not a prompt on the phone asking to trust the PC again.
Last resort, wipe the whole iFakelocation folder and download and start fresh.

**Comment by kimmmchung** [comment]
I've tried to delete and re-download, still no luck. :( thanks though.

**Comment by bgktmxg** [comment]
Ok I think I see the issue, folder needs to be named 13.3.1 as that is the current ios version. For me at least

**Comment by kimmmchung** [comment]
Even though I’m on 13.3? 
![8F656B7B-1757-4F20-B9CA-A41962AA5033](https://user-images.githubusercontent.com/60998501/74403354-0b8dae80-4e7b-11ea-9aa1-32e296ea1d54.jpeg)

**Comment by bgktmxg** [comment]
Nah, 13.3 should be right for you. Im out of ideas :(

You dont have any apps open on your phone that are currently using location?

**Comment by kimmmchung** [comment]
Nah, you’ve helped enough! Thanks for your help so far. Um not that I know of... I’ve been following and using the exact same steps as I always have before. This kind of error only popped up now that my stupid phone updated to 13.3 -_- wish I can go back to v13...

**Comment by master131** [comment]
@kimmmchung See #12 and see if it works.

**Comment by kimmmchung** [comment]
Hi @master131, thank you so much for this! However I just tried now and still not working :( Still giving out the **Unable To Mount Developer Image** error message...

**Comment by master131** [comment]
@kimmmchung Are you able to try the latest version?

**Comment by kklyc** [comment]
Just signed up to GitHub to say thank you to @master131 , you truly are a master. Adding my two cents to this error message, the error disappears when my iphone screen is unlocked.
