### ISSUE TITLE
Does not set Location

### ISSUE THREAD

**Issue by armn77** [master131/iFakeLocation#110]
Hi, I have installed the latest dmg but it does not set fake location ... it was working fine before

**Comment by armannch** [comment]
I get the attached message

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/118029091/203450382-ca782686-7bac-45cb-9028-3ab09aa16a64.png">

**Comment by armannch** [comment]
Ok it works you needed to say Turn On Developer Mode in iPhone. I was looking for it on the MAC ;-)
