### ISSUE TITLE
Location does not set

### ISSUE THREAD

**Issue by coinage77** [master131/iFakeLocation#114]
Location will not set - currently running Mac OS Big Sur 11.7 and iPhone 11 16.1.2

**Comment by master131** [comment]
You need to provide more information - what do you mean that location will not set? Are there any messages appearing on iFakeLocation? Have you tried restarting your phone?

**Comment by coinage77** [comment]
When I found the location I want to set, I click on the set fake location (the button stays highlighted) however it does not actually set the locaton and no errors appear. Usually it mentions if it has successfuly set to the chosen location

<img width="1186" alt="Screen Shot 2022-12-29 at 10 05 15 am" src="https://user-images.githubusercontent.com/119370056/209890159-60d74000-4ec5-4968-a481-476bc83fc699.png">

**Comment by coinage77** [comment]
Now it is coming up with the following error message after a few attempts at restarting and reinstalling:

Unable to mount developer image.

**Comment by coinage77** [comment]
All of a sudden it's now working :)
