### ISSUE TITLE
Device iOS not supported/unable to Mount 

### ISSUE THREAD

**Issue by PeterOzB** [master131/iFakeLocation#12]
Hi
My iPhone X updated to iOS 13.3.1 and now ifake either gives me “unable to mount” or “iOS not supported”. 

I have updated iTunes to latest version. 
Have deleted ifake and re downloaded latest version from here: https://github.com/master131/iFakeLocation/releases

Once unzipped there is no folder for developer images - so I create one manually create another folder within named “13.3” and then attach the two files from here:
https://github.com/master131/iFakeLocation/blob/master/README.md

There is no image for 13.3 so I download 13.1. 

Still no success, pls help.

**Comment by master131** [comment]
https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/raw/master/Developer%20Disk%20Image/13.2%20(17B102)/DeveloperDiskImage.dmg
https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/blob/master/Developer%20Disk%20Image/13.2%20(17B102)/DeveloperDiskImage.dmg.signature

Try these instead for 13.3.

**Comment by PeterOzB** [comment]
Hey
Thank you so much for this.
I haven’t used these new images as I got it working with my iPad - the 13.1 images worked for my iPad which is on iOS 12.2

As long as one is working I don’t want to risk it!!!

Sent from my iPhone

On 16 Feb 2020, at 2:53 pm, master131 <notifications@github.com> wrote:

﻿

https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/raw/master/Developer%20Disk%20Image/13.2%20(17B102)/DeveloperDiskImage.dmg
https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/blob/master/Developer%20Disk%20Image/13.2%20(17B102)/DeveloperDiskImage.dmg.signature

Try these instead for 13.3.
