### ISSUE TITLE
Why depend on openssl-1.0 on Linux?

### ISSUE THREAD

**Issue by Moxinilian** [master131/iFakeLocation#121]
Hey!

On Linux, iFakeLocation depends on openssl-1.0, which is an ancient release of OpenSSL that is better not installed. I only keep it for iFakeLocation, but is there any reason why this is a dependency, and not say a newer version of OpenSSL?

I don't really know how C# projects work so sorry if this is a common problem!

**Comment by master131** [comment]
It's an dependency used by libimobiledevice which is one of the libraries used by iFakeLocation. I'm using a public wrapper for that library so I don't have control over that unfortunately.

**Comment by Moxinilian** [comment]
Oh, that's interesting. I'll check it out there! Thanks.
