### ISSUE TITLE
IOS 16 Public Beta iOS 16.4 (20E5212f)

### ISSUE THREAD

**Issue by shibuthomas2023** [master131/iFakeLocation#123]
Hi There,

I am not able to set the fake location as it is coming up with the error message as "Your device's iOS version is not supported at this time." Please see the attached Screenshot. Please advise when I can use the application.
![Screenshot 2023-02-28 195936](https://user-images.githubusercontent.com/126559167/221803773-001f00c0-b2d1-4f28-b75b-4653d31a9734.png)

**Comment by master131** [comment]
Can you try now?

**Comment by shibuthomas2023** [comment]
Hi There,

Now it is coming up as "Unable to start simulatelocation service.". Please see the attached 
![Screenshot 2023-02-28 195936](https://user-images.githubusercontent.com/126559167/221807338-283100cc-e718-4dbb-aa5f-cb1294719a77.png)

**Comment by shibuthomas2023** [comment]
Thanks for your prompt response. I can confirm now it is working perfectly as it was meant to be... :)
👍
