### ISSUE TITLE
Suggestion / Enhancement

### ISSUE THREAD

**Issue by raviteja10081996** [master131/iFakeLocation#13]
first of all I thank you for your giving us this project for playing 

here are some idea I like 

Can we simulate location via wifi network (no need of cable thing)
Can we simulate location with location coords like lat, long (some auto paste  from clipboard feature when coords are copied )
can we have menu called favourites location where we save lat, long with a some name and can simulate location by tapping them 
last but no least some ui tweaking for better look as look matter :P

**Comment by sukrubezen** [comment]
Also possibility of adding a GPX file would be cool.
I am also a programmer but I have not worked on Windows programs before, I will have a look into the code and see if I can manage to do so and if I do, gonna send a PR

**Comment by raviteja10081996** [comment]
@sukrubezen if you this for Pokemon go gpu won't be useful as they can detect the movement and red warning fro sure for any other purpose you can the gpx mode
