### ISSUE TITLE
Your devices IOS version is not supported at this time

### ISSUE THREAD

**Issue by shibuthomas2023** [master131/iFakeLocation#132]
Hi Master,

Could you please help me to run the application as recently updated the IOS Beta version iOS16.5 (20F5028e) Beta Version.

Please see the attached screenshot.

Hope to hear from you soon.

![image](https://user-images.githubusercontent.com/126559167/229331541-b0989272-1cad-4ebd-a409-ac48f165b06b.png)

**Comment by master131** [comment]
Can you see if it works now?

**Comment by shibuthomas2023** [comment]
Hi Master,

I can confirm now it is working fine. Much Appreciated.

Thanks

**Comment by bigcat133** [comment]
Because the xcode developer development package provided by the dependent project has not been updated, it can only support below 16.1 at present
[https://github.com/haikieu/xcode-developer-disk-image-all-platforms](url)
