### ISSUE TITLE
Incorrect device detection/not detecting

### ISSUE THREAD

**Issue by dealhunter89** [master131/iFakeLocation#136]
Having a trouble from past few weeks. I was using iPhone XR (iOS 16.3.1 Under my name) for a very long time to connect and set location, but recently started using the spare mobile iPhone X (iOS 16.4.1 Under souse's name). This app worked fine once on the iPhone X but since after that every time I connect iPhone X, the Device Name shows my iPhone XR device name with iOS 16.3.1 and not detecting the actual device iPhone X that is connected. I am using Macbook Pro (2015) with OS 12.6.3. 

I have uninstalled and re-installed iFakeLocation software (1.7) but that didn't solve the problem. I have also tried connecting my Macbook to mobile data and launching the app via Terminal but no help. Please assist.

**Comment by master131** [comment]
Are you able to access the device via Finder without issues?

**Comment by dealhunter89** [comment]
> Are you able to access the device via Finder without issues?

No

**Comment by dealhunter89** [comment]
> Are you able to access the device via Finder without issues?

I have connected iPhone 14 Pro Max and it worked. Looks like my iPhone X and iPhone XR have trust issues with the Macbook. Thanks @master131, I am very grateful of this app.

Note for someone interested in the issue background: Iphone X flashes Trust device screen continuously and doesn't even let me hit the button but the phone is still charged when connected to Macbook and iPhone XR is not even connected/detected with macbook and the charge symbol doesn't show up, so these issues seem to be devices related rather than this wonderful App.
