### ISSUE TITLE
Your IOS Device is not supported

### ISSUE THREAD

**Issue by shibuthomas2023** [master131/iFakeLocation#138]
Hi,
Today I tried to use the application and came up with the error message as “Uour IOS Device is not supported”.
My iPhone version is as below:-
iOS 16.6 (20G5026e)

Your quick response would be highly appreciated.
Thanks

**Comment by master131** [comment]
Can you please try again?

**Comment by shibuthomas2023** [comment]
Hi Master,
I can confirm it is working fine now.
Thanks
