### ISSUE TITLE
iOS 13.4 Unable to mount

### ISSUE THREAD

**Issue by Slugoid** [master131/iFakeLocation#14]
Tried renaming the 13.3 folder to 13.4 and using the 13.2.2/13/3 images but unable to mount.  Seems like it needs new 13.4 dev images.

**Comment by bgktmxg** [comment]
Yeah looks to be the same here, none of the old tricks work. Hopefully its able to be sorted, I use this a couple of times a week :)

**Comment by master131** [comment]
@Slugoid Please try the latest version.

**Comment by Slugoid** [comment]
I have updated one device to 13.4.1 and it still "unable to mount developer image".  On another device running 13.3.1 it is still working fine.

**Comment by master131** [comment]
@Slugoid @bgktmxg Thanks - I think I can fix this - will try downgrading one of the libraries and upload a new version.

**Comment by master131** [comment]
I've just uploaded v1.4.1, can you guys give that a try? @Slugoid  @bgktmxg

**Comment by bgktmxg** [comment]
Working perfectly thanks! What happened to your Patreon? I was subbed to it and just realised it stopped late last year

**Comment by master131** [comment]
@bgktmxg I've become self-sufficient since then so I didn't feel the need to have a Patreon anymore.

**Comment by bgktmxg** [comment]
Awesome. Thanks again for the app

**Comment by Slugoid** [comment]
All working now on 13.4.1. Thanks a lot!
