### ISSUE TITLE
iOS 17 (21A5312c)

### ISSUE THREAD

**Issue by shibuthomas2023** [master131/iFakeLocation#143]
Hi There,
After upgrading to IOS 17, I am not able to use iFakeLocation.
Please see the below screenshot.
![image](https://github.com/master131/iFakeLocation/assets/126559167/9828527a-8fca-43fe-9b60-6f484278fbd6)

Could you please assist at your earliest possible.

Thanks

**Comment by master131** [comment]
iOS 17 is not supported at this time due to large changes made by Apple. Please keep an eye on updates in https://github.com/master131/iFakeLocation/issues/141.
