### ISSUE TITLE
No images for 14 Pros running iOS 17?

### ISSUE THREAD

**Issue by Sneethan** [master131/iFakeLocation#146]
I used to use this on an older iphone and it worked great, and I thank you for your work.
A few months ago i upgraded to a 14 Pro, and now whenever I try to spoof location I get this error.
![image](https://github.com/master131/iFakeLocation/assets/53156475/9aec4141-24b5-45ba-b82b-08cf3d75dd27)
Is there a specific file that needs to be made for 14 Pros?

**Comment by Dan-Wood** [comment]
See https://github.com/master131/iFakeLocation/issues/141
