### ISSUE TITLE
new error after update of new i17 "The developer images for the specified device are missing"

### ISSUE THREAD

**Issue by shehryawr** [master131/iFakeLocation#149]

**Comment by PrabhaviP** [comment]
Thanks for this amazing sw. 
I have the same issue. Tried to manually add a DeveloperImage folder with the iOS17 image provided under releases (https://github.com/master131/iFakeLocation/releases/download/v1.7.0/iPhone-iPadOS-Personalized-17.0.zip), renamed the dmg and signature files as instructed but still get the same error. The folder gets picked, but the image cannot be mounted...

**Comment by scriptxyz** [comment]
Same error

**Comment by master131** [comment]
iOS 17 is not supported at the moment. See https://github.com/master131/iFakeLocation/issues/141.
