### ISSUE TITLE
Any support for iOS 15.8?

### ISSUE THREAD

**Issue by ozziekhoo** [master131/iFakeLocation#162]
Shouldn't have just updated my spare 6S+ without checking if this would work :/

**Comment by trueelite1** [comment]
Also have the same problem T_T

**Comment by whlem** [comment]
use image 15.5. Rename the folder from 15.5 -> 15.8

**Comment by ozziekhoo** [comment]
> use image 15.5. Rename the folder from 15.5 -> 15.8

TY!

**Comment by ozziekhoo** [comment]
> use image 15.5. Rename the folder from 15.5 -> 15.8

TY

**Comment by woei66** [comment]
you can download 15.8 from https://github.com/JinjunHan/iOSDeviceSupport/tree/master/iOSDeviceSupport

**Comment by Aniruddha22Gupta** [comment]
how much time does it take for *Iphone is busy: Making Iphone ready for development*. I found this issue while fixing this. It takes forever. Please someone help!!
