### ISSUE TITLE
is it possible to use on a cloud server?

### ISSUE THREAD

**Issue by dethanzhang** [master131/iFakeLocation#20]
i just installed dotnet on my ecs(ubuntu 18), and run iFakelocation.
then it turned out "Unable to start iFakeLocation using default web browser."

so i'm wondering if it's possible to run without a web browser.

and even, if i build a connection between my iphone & ecs. i can fake my location anywhere anytime.

**Comment by master131** [comment]
Not out of the box. That would be up you to implement - also I'm not sure if the library I'm using works wirelessly?

**Comment by dethanzhang** [comment]
> Not out of the box. That would be up you to implement - also I'm not sure if the library I'm using works wirelessly?

ok. I found the original project could run on Linux.(libimobiledevice). About wirelessly, ifakelocation can set iphones’ location wirelessly, not until they were connected to the pc once using cable. 

Actually i just want to change my location through terminal on win/linux.

**Comment by master131** [comment]
If you are looking for a command-line solution, there is already a command-line utility that comes with libimobiledevice called idevicesetlocation.

**Comment by dethanzhang** [comment]
> If you are looking for a command-line solution, there is already a command-line utility that comes with libimobiledevice called idevicesetlocation.
> 
> You need to mount the developer image first using ideviceimagemounter. Both support the --network switch.
> 
> idevice_id utility can be used to list all device UDIDs which are required as parameters for the above utilities.

yes thx.
i've already compiled imobiledevice tools for mac. still figuring out how to build a win ver tho
