### ISSUE TITLE
Does it support 13.6 beta？

### ISSUE THREAD

**Issue by 775405984** [master131/iFakeLocation#21]
Just wondering.
@master131

**Comment by master131** [comment]
Not at the moment. If you want to have support for 13.6-beta then you will need to supply the developer images yourself as I don't see them published anywhere.

If you have a Mac and Xcode 11.6 beta which has the SDK for iOS 13.6, you'll find the images here:
~/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/
