### ISSUE TITLE
Support for iOS 14 please

### ISSUE THREAD

**Issue by 775405984** [master131/iFakeLocation#22]
Already downloaded iOS 14 disk image, but it won't work.

**Comment by 775405984** [comment]
@master131

**Comment by master131** [comment]
Can you tell me what OS you're running? If you are on MacOS, the developer image needs to go inside the *.app itself (right-click > Show Package Contents). You will have better luck copying the image using the Terminal.

iFakeLocation.app/DeveloperImages/14.0/....

**Comment by 775405984** [comment]
I'm using Windows 10. &nbsp;@master131

**Comment by master131** [comment]
What's the actual error? You just said that it doesn't work.

**Comment by 775405984** [comment]
Unable to start simulatelocation service.

@master131

**Comment by master131** [comment]
There might be some change made in iOS 14, but I don't have any device that can run it at the moment so I can't really give any solutions unfortunately. I've seen people recommend 3utools, you can give that a try.

**Comment by walshy1009** [comment]
Just got it working on iOS 14 beta 1 on my Mac.

**Comment by bgktmxg** [comment]
> 
> 
> Just got it working on iOS 14 beta 1 on my Mac.

Any suggestions to getting it working on Windows? Thanks

**Comment by alvinnguyen** [comment]
@walshy1009 any tips on getting it working on iOS 14? I'm getting the same error of Unable to start simulatelocation service.

**Comment by bgktmxg** [comment]
> 
> 
> @walshy1009 any tips on getting it working on iOS 14? I'm getting the same error of Unable to start simulatelocation service.

Master will most likely update it to work natively now that 14 is actually out, as he has done in the past

**Comment by lihe1314** [comment]
iPhone 6s Plus running on iOS 14 after receive official firmware update pushed from Apple
![image](https://user-images.githubusercontent.com/1768237/93426261-07d57500-f8ff-11ea-9dee-1fd32d39d932.png)

I am using macos, the developers image does downloaded inside the app content, I can see DeveloperDiskImage and the signature file created.

however still having the same issue as "Unable to start simulatelocation service" on click the fake location button
![image](https://user-images.githubusercontent.com/1768237/93426231-f8562c00-f8fe-11ea-8a0d-4b4950301e59.png)

**Comment by xiyanghu** [comment]
win10 with ipadOS 14 has the same issue

**Comment by bgktmxg** [comment]
It wont work on any device that's running 14 until its updated.

**Comment by jay31363** [comment]
Same issue with IOS 14 on iPhone X on PC running windows 10.

**Comment by alvinnguyen** [comment]
FWIW if you guys have an Apple Developer account and Xcode - you can always connect, run a dummy app, simulate location via Xcode. It will simulate the location on your device for all the apps.

**Comment by lihe1314** [comment]
Yeah, that is the way, but not as elegant as using this app to mimic the
location.

**Comment by master131** [comment]
I don't use an iDevice as my daily driver so I have to borrow one from another family member. Once it's updated to iOS 14 I'll see what I can do but no guarantees - hopefully the fix is simple.

**Comment by ymmf80** [comment]
I downloaded the ios 13.6 developer image instead of 13.7 or 14.0 and it works now.

**Comment by BergenSoft** [comment]
I cannot confirm this.

**Comment by ymmf80** [comment]
> I cannot confirm this.

I used it on a Mac. I unzipped the 13.6.zip, right click to open package content of iFakeLocation and moved the unzipped folder under \bin\DeveloperImages\ 

When I run it it would show a message saying it is downloading Developer Images, and then it worked. I have just tried again and it was fine.

**Comment by BergenSoft** [comment]
Tried the same on Windows. iFakeLocation has downloaded the ios 14 developer image, but it failed with the same message.

**Comment by jackypeacful** [comment]
> > I cannot confirm this.
> 
> I used it on a Mac. I unzipped the 13.6.zip, right click to open package content of iFakeLocation and moved the unzipped folder under \bin\DeveloperImages\
> 
> When I run it it would show a message saying it is downloading Developer Images, and then it worked. I have just tried again and it was fine.

doesnot work on ios 14, I am sure that you are not using ios 14

**Comment by ymmf80** [comment]
> 
> doesnot work on ios 14, I am sure that you are not using ios 14

I am definitely on iOS14.

**Comment by jackypeacful** [comment]
> > doesnot work on ios 14, I am sure that you are not using ios 14
> 
> I am definitely on iOS14.
> 
> The only thing I could ever think of is initially both 13.6 and 14.0 dev image folders were within the "opened package content". But I have deleted the 14.0 folder afterwards and it still works.

Did you rename 13.6? otherwise 14.0 will automatic download if you don't have a folder call 14.0 (if you are actually on ios 14.0).

**Comment by ymmf80** [comment]
> > > doesnot work on ios 14, I am sure that you are not using ios 14
> > 
> > 
> > I am definitely on iOS14.
> > The only thing I could ever think of is initially both 13.6 and 14.0 dev image folders were within the "opened package content". But I have deleted the 14.0 folder afterwards and it still works.
> 
> Did you rename 13.6? otherwise 14.0 will automatic download if you don't have a folder call 14.0 (if you are actually on ios 14.0).

No I didn't rename. And I think you are correct that it just automatically downloaded 14.0 and hence both 13.6 and 14.0 exist under bin\DeveloperImages\.

**Comment by jackypeacful** [comment]
> > > > doesnot work on ios 14, I am sure that you are not using ios 14
> > > 
> > > 
> > > I am definitely on iOS14.
> > > The only thing I could ever think of is initially both 13.6 and 14.0 dev image folders were within the "opened package content". But I have deleted the 14.0 folder afterwards and it still works.
> > 
> > 
> > Did you rename 13.6? otherwise 14.0 will automatic download if you don't have a folder call 14.0 (if you are actually on ios 14.0).
> 
> No I didn't rename. And I think you are correct that it just automatically downloaded 14.0 and hence both 13.6 and 14.0 exist under bin\DeveloperImages.

Then your method doesn't work for me TT . I have tried  your method and placed folder in bin. My folder now have both 13.6 and 14.0. As a result, the simulation is unable to operate.

**Comment by ymmf80** [comment]
> > > > > doesnot work on ios 14, I am sure that you are not using ios 14
> > > > 
> > > > 
> > > > I am definitely on iOS14.
> > > > The only thing I could ever think of is initially both 13.6 and 14.0 dev image folders were within the "opened package content". But I have deleted the 14.0 folder afterwards and it still works.
> > > 
> > > 
> > > Did you rename 13.6? otherwise 14.0 will automatic download if you don't have a folder call 14.0 (if you are actually on ios 14.0).
> > 
> > 
> > No I didn't rename. And I think you are correct that it just automatically downloaded 14.0 and hence both 13.6 and 14.0 exist under bin\DeveloperImages.
> 
> Then your method doesn't work for me TT . I have tried your method and placed folder in bin. My folder now have both 13.6 and 14.0. As a result, the simulation is unable to operate.

Sorry couldn't be of help. I am still puzzled why it is all fine for me. Maybe try re-downloading the 13.6.zip, delete everything under the bin\DeveloperImages and try again?

**Comment by Huanpierre** [comment]
Also running into the same issue on ios 14 with the "Unable to start simulatelocation service" error.

Hopefully this is updated soon to be compatible with it.

**Comment by macsir** [comment]
is there a fix yet?

**Comment by master131** [comment]
The simple explanation is that it looks like the incorrect developer image for iOS 14 was uploaded to one of the sources used by iFakeLocation. If you swap it out with this one, it will work:
https://github.com/haikieu/xcode-developer-disk-image-all-platforms/raw/master/DiskImages/iPhoneOS.platform/DeviceSupport/14.0.zip

**Comment by master131** [comment]
iFakeLocation v1.4.2 has been published for Windows & macOS.

https://github.com/master131/iFakeLocation/releases

**Comment by Huanpierre** [comment]
> iFakeLocation v1.4.2 has been published for Windows & macOS.
> 
> https://github.com/master131/iFakeLocation/releases

Just tried this new version on windows with ios 14 and no luck, still the same error, ended up replacing the img with the below as recommend previously and it works now 

https://github.com/haikieu/xcode-developer-disk-image-all-platforms/raw/master/DiskImages/iPhoneOS.platform/DeviceSupport/14.0.zip

**Comment by master131** [comment]
Thanks for that @Huanpierre, I've updated it to v1.4.3 which now prefers that ZIP source instead of the other one.

**Comment by Huanpierre** [comment]
> Thanks for that @Huanpierre, I've updated it to v1.4.3 which now prefers that ZIP source instead of the other one.

Fantastic! thank you very much! 

Can confirming its working now on windows with ios 14

If someone else can confirm on mac and then maybe close this thread by dev.

**Comment by walshy1009** [comment]
> > Thanks for that @Huanpierre, I've updated it to v1.4.3 which now prefers that ZIP source instead of the other one.
> 
> Fantastic! thank you very much!
> 
> Can confirming its working now on windows with ios 14 with ver 1.4.3
> 
> If someone else can confirm on mac and then maybe close this thread by dev.

Can confirm that it's working on Mac Catalina 10.15.7, using my iPhone 11 Pro Max on iOS 14.0.1 to fake my location.

**Comment by BergenSoft** [comment]
Can confirm it works under windows. Thank
