### ISSUE TITLE
failed to open on the latest update of 13.6 on ipad 5th generation.

### ISSUE THREAD

**Issue by Hin38** [master131/iFakeLocation#25]
Hi, could not open the app due to the latest update of IOS13.6 on ipad. Please update the developer images

**Comment by master131** [comment]
Are you using a Mac? Can you please try redownloading the application from the Releases page. There was an issue that stopped the developer images from being downloaded on macOS.

**Comment by Hin38** [comment]
I have redownloaded the application and the developer images several times, and still can't launch it.Could be coming from the latest update of the IOS 13.6

**Comment by Hin38** [comment]
![Screen Shot 2020-07-26 at 8 31 58 pm](https://user-images.githubusercontent.com/68635699/88728059-355e3780-d174-11ea-8c80-b61bd1fe2681.png)

**Comment by master131** [comment]
@Hin38 The latest release (v3-dmg) should fix the issue on macOS.

**Comment by Hin38** [comment]
Hello,
          The issue has been fixed 🙂   thank you very much.

You guys are the best.

Kind regards

Hin
________________________________
