### ISSUE TITLE
Possible Fix for OS Catalina dlyb error messages? (Testers needed please) 

### ISSUE THREAD

**Issue by PrawnMan** [master131/iFakeLocation#30]
I think I got it working on my sisters Mac OS Catalina, but shes gone and I havent got a mac of my own to test it out on. If others could try out what I did, please tell me if it helps 

I 'cd' to the directory of iFakelocation using terminal (I had put it in /Applications/iFakeLocation/). Then, when you're in the directory with the executable, put the following command into terminal: 

`xattr -d com.apple.quarantine `find . -name 'lib*.dylib'`
`

From my understanding( Again, I dont have a mac so If Im wrong or doing something harmful/dangerous, please tell me), but in Catalina, any files downloaded using a web browser from the internet has some sort of "quarantine attribute" set. Doing the above command to all the files inside the iFakeLocation Dir allows the iFakeLocation executable to download and run things without a flurry of "dlyb" error messages. I was able to spoof my location then. 

Could anybody with OS Catalina who gets those error messages and is unable to spoof the location try it out for me and see how it goes for them?

**Comment by walshy1009** [comment]
I got them working by going to system preferences, security and privacy and clicking the 'allow' prompt that came up for it at the bottom of the window. You might have to do it a few times but you'll eventually get the option to click 'open' at which point it shouldn't hassle you again.
