### ISSUE TITLE
.NET 2.2 has been EOL, cannot build on Linux

### ISSUE THREAD

**Issue by galaxy001** [master131/iFakeLocation#31]
.NET 2.2 has been EOL as <https://docs.microsoft.com/en-us/dotnet/core/install/linux>.

I tried with `dotnet-sdk-2.2.207-linux-x64.tar.gz`, however, it says :
```
Build FAILED.

/home/galaxy/git/iFakeLocation/ins/dotnet-sdk-2.2.207/sdk/2.2.207/Microsoft.Common.CurrentVersion.targets(1183,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/galaxy/git/iFakeLocation/iFakeLocation/iFakeLocation.csproj]
```

Would you use .NET 3.1 instead ?
3.1.8 LTS will be EoL at December 3, 2022 as <https://dotnet.microsoft.com/platform/support/policy/dotnet-core>.

**Comment by master131** [comment]
Linux is currently not a priority; but the project targets multiple frameworks. It looks like it's trying to target against .NET 4.5 so you might need to fix your build parameters (ie. the -f parameter).

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build

**Comment by galaxy001** [comment]
I find '.NET Framework' has disappeared since .NET Standard v2.1 <https://docs.microsoft.com/en-us/dotnet/standard/net-standard>.
However, after remove `net45` from `iFakeLocation.csproj`, `dotnet build` build only a dll file `./iFakeLocation/bin/iFakeLocation.dll`.

Would you help me on this ?

**Comment by master131** [comment]
In Program.cs, update the preprocessor directives.

from:
#if NETCOREAPP2_2
to:
#if NETCOREAPP3_1
