### ISSUE TITLE
Support for IOS 14.1 please. "Your device's iOS version is not supported at this time."

### ISSUE THREAD

**Issue by briseagle** [master131/iFakeLocation#34]
Hi @master131 

Are you able to update to Support for IOS 14.1 please?
I am running v1.4.3 but not working with 14.1 yet. 

Error "Your device's iOS version is not supported at this time."

I made the stupid mistake of updating IOS earlier today, not thinking it would break this software. 

Thanks in advance for all the hard work you do.

**Comment by ingenieurmt** [comment]
I tried to load a 14.1 Developer Image manually in the DeveloperImages folder, but the one I have (https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.1) doesn't seem to be working. I get the error "Unable to mount developer image" when I click "Set Fake Location".

**Comment by briseagle** [comment]
Excellent - thanks. I will try that myself as well then

> I tried to load a 14.1 Developer Image manually in the DeveloperImages folder, but the one I have (https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.1) doesn't seem to be working. I get the error "Unable to mount developer image" when I click "Set Fake Location".
> 
> EDIT: Scratch that, seems to be working now. I just needed to disconnect and reconnect my iPhone.

**Comment by briseagle** [comment]
Resolved for me as well - thanks
