### ISSUE TITLE
iOS 14.1 Support

### ISSUE THREAD

**Issue by alvinnguyen** [master131/iFakeLocation#35]
Hi guys,

Not sure if it's just me but I'm getting "Your device's iOS version is not supported at this time." with iOS 14.1 devices.

I've got the DeveloperDiskImage in but still no good.

**Comment by master131** [comment]
Please try the latest v1.5.0 update and see if it fixes your issue; I've tested on an iPad running 14.1 and it works now.

**Comment by alvinnguyen** [comment]
All good, thanks a lot as always for your efforts.
