### ISSUE TITLE
Not working with iOS 12.4

### ISSUE THREAD

**Issue by eggsxi** [master131/iFakeLocation#4]
Just tried to lock and got an error - Your device's iOS version is not supported at this time.

Thanks for the ongoing support Master131 !

EDIT: Ignore - I Renamed the "12.3" folder in DeveloperImages to "12.4" and it works.

**Comment by master131** [comment]
Yes, as previously mentioned in another issue if you already have locked in successfully with iOS 12.3, simply renaming the folder named "12.3" inside Developer Images to "12.4" will solve the issue. I'll update the README later to explain this.
