### ISSUE TITLE
14.3 support please

### ISSUE THREAD

**Issue by macsir** [master131/iFakeLocation#43]
After downloading 14.3 images from the too. It is showing this error:
Unable to mount developer image.

**Comment by sandscruise** [comment]
I am also getting the same error "Unable to mount developer image."

**Comment by theg00s3** [comment]
it works on ios 14.3 for me

**Comment by master131** [comment]
iOS 14.3 should be functioning; please ensure that you PC is trusted with your iDevice and that you can connect on iTunes. After that, shutdown iTunes and try again.
