### ISSUE TITLE
iOS 14.4 support please

### ISSUE THREAD

**Issue by alwynpan** [master131/iFakeLocation#44]
Please support iOS 14.4. Thanks.

**Comment by master131** [comment]
I don't have access to the developer images for iOS 14.4 and hoping a kind soul can share it online.

**Comment by master131** [comment]
OK, I've managed to source the developer image for iOS 14.4, can you give it another try? @alwynpan

**Comment by alwynpan** [comment]
Hi @master131, sorry for the late reply. I created a PR to update the disk image repo with iOS 14.4. Would you mind making a release or kindly let me know how to build the app so I can try? Thanks muchly.

**Comment by master131** [comment]
Not sure what PR you are referring to but I've already made the change for iOS 14.4, please try again with v1.5.0.

**Comment by alwynpan** [comment]
@master131 thank you so much. I can confirm it is now works with iOS 14.4.
