### ISSUE TITLE
Developer disk image 14.4.2

### ISSUE THREAD

**Issue by grillsum** [master131/iFakeLocation#47]
anyone knows where to find the disk image for 14.4.2 ? been trying to search the web for it

**Comment by master131** [comment]
iOS 14.4/14.4.1/14.4.2 developer images are all the same; they don't change for patches to existing iOS versions....

**Comment by kuro123456723456u** [comment]
> iOS 14.4/14.4.1/14.4.2 developer images are all the same as 14.4; they don't change for patches to existing iOS versions.

what should I do if I press “set fake location” and the application just take forever to set location for MacBook and eventually an error says “iFakeLocation stopped responding”? I tried multiple times and even re-download it the same issue keep happening
