### ISSUE TITLE
Unable to Mount Developer Image

### ISSUE THREAD

**Issue by a874785874785** [master131/iFakeLocation#48]
iOS 14.4.2  
Facing below two error when try to set location. 

Unable to Mount Developer Image
Mount failed with status: N/A and error: ImageMountFailed

Tried download the image directly for iOS 14.4.2 and replace in folder 14.4 under DeveloperImages

Still pops up the error. 

Tried both under Windows and Mac. 

Same error, any hint. It used to work last week after re-download but tried today still no luck

**Comment by master131** [comment]
Few things to check/try:
1. Does iTunes recognise your device? If not, check your USB connection.
2. Is iTunes actively open? If it is, please close it because it interferes with iFakeLocation.
3. Have you tried restarting your device?

**Comment by a874785874785** [comment]
@master131  you are genius, i think the issue is the unlock, i will double verify. It works now. will also check in windows and update here
