### ISSUE TITLE
Please add support/compile for ios14.6

### ISSUE THREAD

**Issue by captainfalcon23** [master131/iFakeLocation#52]
Looks like support was added for ios 14.6 but a new version not compiled and added to "releases".

**Comment by master131** [comment]
There is no need to compile a new version, it pulls the latest information automatically...

**Comment by captainfalcon23** [comment]
> There is no need to compile a new version, it pulls the latest information automatically...

Are there any known issues with ios14.6? It won’t detect my phone. It used to work fine with ios14.5 and 14.4.

**Comment by master131** [comment]
Not that I am aware of; was able to get it working without issue on an iPad Air 2. Haven't had anyone else report issues. Does iTunes detect your phone for starters?

**Comment by captainfalcon23** [comment]
> Not that I am aware of; was able to get it working without issue on an iPad Air 2. Haven't had anyone else report issues. Does iTunes detect your phone for starters?

Ahh I figured it out. For some reason, I had to trust iTunes to access my iPhone. After trusting the machine (which I've previously used, and was previously trusted) it worked! :)
