### ISSUE TITLE
nothing happened after I double clicked iFakeLocation.exe

### ISSUE THREAD

**Issue by sarphi** [master131/iFakeLocation#55]
It was working perfectly before but not after I re-installed Windows 10(64 bit) recently. I can see the command window pop-up then sort of disappeared, both iTunes and .NET Framework 4.8(latest version) were installed, also tried to change the compatibility mode to the previous Windows version, disable the anti-virus software, etc. Unfortunately none of these actions makes it working. could you think of anything that I can try? Please let me know, thanks so much.

**Comment by master131** [comment]
Try launching iFakeLocation via Command Prompt and see if the message/error remains on the screen.

> cd /d "C:\Users\sarphi\Desktop\iFakeLocation"
> iFakeLocation.exe

**Comment by sarphi** [comment]
it shows "Failed to load necessary files to run iFakeLocation", did I miss something?

**Comment by master131** [comment]
Check that you have Visual C++ 2015 Redistributable installed and try again.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by sarphi** [comment]
There are a few of the various versions that had been installed already, but still not working, kind of weird.

![image](https://user-images.githubusercontent.com/47906255/130338214-cc37e5b8-59aa-4dbb-985f-d9460e71b36d.png)

**Comment by sarphi** [comment]
Hi master131,
It's been a while, I hope you are well. After applying the regular windows update, seems the problem has been fixed for some reason, works perfectly now, thank you and I'm going to close this issue. Much appreciated for help.

**Comment by YozoraEvans** [comment]
If anyone reads this, where's the exe file ? I downloaded the zip file there's no exe,
