### ISSUE TITLE
OpenStreetMap CORS Issue

### ISSUE THREAD

**Issue by change-agent** [master131/iFakeLocation#56]
I have been using iFakeLocation for a while, but today the map isn't loading. 

When I opened the Chrome console, I noticed the following page error: 
`Access to fetch at 'https://nominatim.openstreetmap.org/search?format=json&q=Australia' from origin 'http://localhost:49215' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

The issues tab says the following:

**Ensure CORS response header values are valid**
>A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request.
>
>To fix this issue, ensure the response to the CORS request and/or the associated preflight request are not missing headers and use valid header values.
>
>Note that if an opaque response is sufficient, the request's mode can be set to no-cors to fetch the resource with CORS disabled; that way CORS headers are not required but the response content is inaccessible (opaque).

Launching Chrome with `chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security` is the only workaround:

![chrome_CrhzBvfW5y](https://user-images.githubusercontent.com/7474791/130324699-92a61ee0-0dfe-44b4-93ea-b7095acb97bd.png)
![chrome_mIOuZguOxF](https://user-images.githubusercontent.com/7474791/130324701-27ef88ce-4579-47df-bcc1-702805a80bb5.png)

**Comment by takax2021** [comment]
Same for me.
"--disable-web-security" worked.

**Comment by master131** [comment]
Hey guys, there must be a bug with OpenStreetMaps; I've just tried just now and it is working fine for me. Can you check again and verify that the issue still persists?

**Comment by takax2021** [comment]
> there must be a bug with OpenStreetMap

I've tried now and it's working.
Thank you.
