### ISSUE TITLE
Unable to start simulatelocation service

### ISSUE THREAD

**Issue by infurioushf** [master131/iFakeLocation#64]
Error: Unable to start simulatelocation service.

I'm running IOS 15.1, developer image folder has 15.1, I've tried deleting and re-installing, I've tried using it on a different computer (first on Windows then on Mac), the phone is unlocked when locking, .NET 5 installed.

Doesn't seem to fix it. Any solutions?

Cheers!

**Comment by master131** [comment]
Have you verified that iTunes can detect the device and has full access to it? I have just tested it myself with an iPad running iOS 15.1 and it worked right out of the box.

**Comment by infurioushf** [comment]
Okay, so it seems to be working now. 
All I did was open the 'Music' app on my MacBook. This seems to have replaced iTunes in the recent models. I was able to change my location afterward. 

However - I am not sure if it was by chance that the 'Music' app fixed it or if simply trying the location spoofer three days later was all that was needed.

**Comment by master131** [comment]
It's hard to say - sometimes these kinds of issues are fixed with a simple reboot as well.
