### ISSUE TITLE
Not detecting iOS device

### ISSUE THREAD

**Issue by mooksjt** [master131/iFakeLocation#65]
Plug device into Win10 computer
I can see the device in File Explorer + ITunes
Cannot detect device in drop down box under Device Name?
Any suggestions? Thanks

**Comment by master131** [comment]
Have you tried clicking the Refresh button? Also make sure iTunes is closed when trying it.

**Comment by mooksjt** [comment]
Thanks Master131. Ending up updating the ITunes and worked.
