### ISSUE TITLE
Mount failed with status: N/A and error: ImageMountFailed

### ISSUE THREAD

**Issue by macsir** [master131/iFakeLocation#66]
ISO 15.1.1 Please help. Thanks.

**Comment by master131** [comment]
- Make sure your iDevice is trusted with your PC/Mac (should be accessible via iTunes or via the Mac Finder).
- If you are on Windows, close iTunes if its running.
- Ensure the device is unlocked.
- Failed everything, try restarting your phone - this has worked when everything else hasn't.

**Comment by macsir** [comment]
Thanks, will try reboot next time. The first three options have been ensured.

**Comment by macsir** [comment]
Yes, the reboot works fine. Thanks.
