### ISSUE TITLE
Unable to Mount disk image 14.3 suddenly

### ISSUE THREAD

**Issue by wonkieinc** [master131/iFakeLocation#67]
This was working well for the last few weeks but suddenly stopped. Device is recognised in Finder etc

Oddly enough my other iPhone on 15.1 has no issue using the same computer/cable

**Comment by master131** [comment]
Have you tried rebooting your phone?

**Comment by wonkieinc** [comment]
Yes many times, tried it both jailbroken and non jailbroken, no luck either way

**Comment by gkcngk** [comment]
I have had the same error on 14.3 all of a suddent. However this has been simply sloved by rebooting the phone.
