### ISSUE TITLE
Location Reset 

### ISSUE THREAD

**Issue by sztoo** [master131/iFakeLocation#71]
I was able to successfully set a location at first, but the location goes away / reset after some time (unplugged from computer). 

Device: iPhone 12 Pro Max
iOS: 15.2.1
macOS: Monterey 12.1 

Does the device need to be continuously connected to the machine to maintain the spoofed location service connectivity?

**Comment by ejkiup159** [comment]
The validity period of each manual connection to the computer debugging position is about 1 day 
If you plan to keep virtual positioning all the time, please connect your computer every other day for set a location
