### ISSUE TITLE
Access to the path '/xxx/xxx/DeveloperImages/9.3/DeveloperDiskImage.dmg' is denied.

### ISSUE THREAD

**Issue by Zer0xPoint** [master131/iFakeLocation#72]
macOS 12.1
ifake 1.6
iPhone 4s 9.3.6
it works well before, But today suddenly not working, error reports like Access to the path '/xxx/xxx/DeveloperImages/9.3/DeveloperDiskImage.dmg' is denied.

try to redownload iOS image file, not working

**Comment by ejkiup159** [comment]
If for whatever reason the automatic developer image retrieval doesn't work, you can manually download them to be used in iFakeLocation. Create a folder called "DeveloperImages" (next to the iFakeLocation executable) and inside that folder make a folder for the iOS version you are running (eg. "12.4", "13.0", etc). Download the matching developer images from the following Github repo and unzip the DeveloperDiskImage.dmg + DeveloperDiskImage.dmg.signature file into the folder you created.
