### ISSUE TITLE
IOS 15.3.1 Your device's iOS version is not supported at this time.

### ISSUE THREAD

**Issue by gooey1234** [master131/iFakeLocation#73]
Hi never got this message before, but Im on 15.3.1 and I'm getting a message that the ios version is not supported. will this be fixed soon? thanks

**Comment by master131** [comment]
iOS 15.3 should be supported; are you sure you have a working internet connection?

**Comment by gooey1234** [comment]
Thanks for getting back to me, i had older version of your app, and it always would download the new updates to phone when ios updated, but it stopped doing that and realised i have to install latest version of app, no worries thanks
