### ISSUE TITLE
Location changing working without cable?

### ISSUE THREAD

**Issue by bgktmxg** [master131/iFakeLocation#78]
So I opened iFakeLocation this morning and noticed my main phone was showing in the device area without even being plugged in.

Out of curiosity I tried to set a location and it worked. How is this possible?

**Comment by master131** [comment]
I believe it's via WiFi syncing:
https://support.apple.com/en-au/guide/itunes/itns3751d862/windows

**Comment by bgktmxg** [comment]
Thanks for the reply, Ive never setup iTunes sync but I disabled my wifi and the device disappeared from iFakeLocation so its definitely related.
It might be the iCloud windows app I run?
