### ISSUE TITLE
Getting error "Unable to start simulatelocation service." with IOS 13.2

### ISSUE THREAD

**Issue by jay31363** [master131/iFakeLocation#8]
I get error saying "Unable to start simulatelocation service." on my iphone X running iOS 13.2.
Developer disk images are downloaded correctly but when I click on a set a fake location, I get that error.

PS: I am using non jailbreak iphone

**Comment by bgktmxg** [comment]
Are you running the latest version of iFakeLocation? I was getting this issue yesterday and I deleted the app and downloaded fresh and it started working again fine

**Comment by jay31363** [comment]
Yes, I have just downloaded it today.
I am using 1.3.1

**Comment by bgktmxg** [comment]
Make sure your personal hotspot is turned off. I know another user that was getting issues because of that

**Comment by jay31363** [comment]
That is off too, turned off wifi as well, still getting the same error.
Does the device has to be jailbreaked ?

**Comment by bgktmxg** [comment]
No jailbreak required. I don't know what your issue is then. Maybe make sure itunes is installed and up to date

**Comment by jay31363** [comment]
Thanks will do. Do I have to leave itunes running in background as well ?

**Comment by bgktmxg** [comment]
Doesn't need to be running in the background. I have a feeling it just installs some drivers when you install it the first time

**Comment by jay31363** [comment]
I have it installed but not up to date version. 
updating both itunes and ios 13.2.2 as well. I will let you know if that fixes it.
Thanks,
Jay

**Comment by jay31363** [comment]
Excellent, update seems to have fixed it.

Thank you for the prompt repose and keep the great work.

**Comment by bgktmxg** [comment]
No worries. FYI im not the owner of this program, just trying to help out :)
