### ISSUE TITLE
Better DiskImage Repo

### ISSUE THREAD

**Issue by joytsay** [master131/iFakeLocation#80]
https://github.com/pdso/DeveloperDiskImage
This repo above has the newest 15.5 DiskImage for download :)
Got [iFakeLocation](https://github.com/master131/iFakeLocation) working following the readme steps: 
https://github.com/master131/iFakeLocation#how-to-make-it-work-on-ios-xx

Unfortuantely the original download link provided:
https://github.com/haikieu/xcode-developer-disk-image-all-platforms/tree/master/DiskImages/iPhoneOS.platform/DeviceSupport hasn't updated 15.5 yet :(

**Comment by master131** [comment]
I have the ability to source the disk images from the official Xcode packages that Apple provide but was busy this week and forgot mid-way. I've updated the sources with the 15.5 image.

![image](https://user-images.githubusercontent.com/1592009/168941554-dee00f36-d113-4c20-b13f-625ba1dc4b89.png)
