### ISSUE TITLE
Not working on iOS 16.0

### ISSUE THREAD

**Issue by weiyifeng** [master131/iFakeLocation#82]
Mount failed with status: N/A and error: ImageMountFailed
I've tried macOS and Win11 x64. I manually replaced the iOS 16 files.
My iPhone is unlocked and screen is on. My computer is trusted. I have access to my iPhone in Finder and iTunes.

**Comment by weiyifeng** [comment]
> Have you tried restarting your phone?

Yes I did. And I've tried my iPhone 12 and iPhone 13 both on iOS 16.
Restarted, unlocked, trusted.

**Comment by master131** [comment]
I don't have the beta installed yet; will have to try installing and see if I can reproduce the issue.

**Comment by master131** [comment]
> > I don't have the beta installed yet; will have to try installing and see if I can reproduce the issue.
> > EDIT - Looks like Apple dropped support for iPad Air Gen 2; will have to get my hands on a more modern device to test with.
> 
> Oh, I just figured it out. I have to turned on developer mode in privacy setting first.

Thanks I have updated the readme accordingly.
