### ISSUE TITLE
Bug in projectzerothree alerts email script

### ISSUE THREAD

**Issue by pouyaman** [master131/iFakeLocation#88]
This is not related to iFakeLocation, however I could not find any other contact information from you.

There is a small bug in the script that comes from https://projectzerothree.info/alerts.html  
Recently this bug is causing constant script fail recently.

Below is the fix:

```patch
@line55:57
-            last_prices[i][1].state == best_prices[i][1].state;
-        if (last_prices[i][1].price != best_prices[i][1].price) {
-          old_price = last_prices[i][1];
+            last_prices[x][1].state == best_prices[i][1].state;
+        if (last_prices[x][1].price != best_prices[i][1].price) {
+         old_price = last_prices[x][1];
```

**Comment by master131** [comment]
The script isn't that great to be honest; there are apps which are probably better. I will look into this later.

**Comment by pouyaman** [comment]
Don't downplay the simplicity of the script mate, I much prefer a quick email than yet another app on my phone 😁

After the fix listed above (which is just correcting the `last_prices` array index to use the `x` instead of the `i` and have been running the script every 5 minutes for the last few hours and haven't had any crashes yet 👍🏼 logic wise it makes sense to have`x` there as that for loop is traversing through the last prices to update them (I think).
