### ISSUE TITLE
iOS 16 beta - Mount failed with status: N/A and error: ImageMountFailed

### ISSUE THREAD

**Issue by ribbox** [master131/iFakeLocation#89]
iOS16 Beta 
iPhone 11
iFakelocation 1.6

iOS16 Developer diskimage downloaded by iFakelocation 

Tried on my wife's iPhone 12 iOS15.5 with no issue.

I rebooted my phone a number of times with no luck.

unable to find the option to enable Developer mode on my phone.

**Comment by master131** [comment]
https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device

**Comment by ribbox** [comment]
Thanks, the option is not showing up on my phone.

**Comment by namtonthat** [comment]
Also not appearing for me - there is only a Lockdown Mode where the Developer Mode should be. 

Any ideas?
![IMG_2B54A6A69FFD-1](https://user-images.githubusercontent.com/91519364/178733997-71fd8305-4dc7-4630-95b3-56abbed3265c.jpeg)

**Comment by master131** [comment]
Can you confirm which iOS 16 beta you are on? I recently updated the iOS 16 image taken from Xcode 14.0 beta 3 - so maybe you need to be on iOS 16 beta 3 if you aren't already on that?

**Comment by master131** [comment]
Found this from WWDC 2022:

![image](https://user-images.githubusercontent.com/1592009/178737836-7a87d65e-f80b-4ac8-b670-084f6fe9ba62.png)

https://developer.apple.com/videos/play/wwdc2022/110344/

So unless you have a Mac handy with Xcode installed, you are out of luck until there is a documented way to do this through libimobiledevice.

**Comment by IonicEcko** [comment]
Anyone know how to try to sideload an app to show the developer mode option without a mac? Would love to be able to do it but just haven't been able to work out how!

**Comment by master131** [comment]
Hi all, the latest version of iFakeLocation now has the ability to enable the hidden Developer Mode toggle without Xcode.

**Comment by EthanBezz** [comment]
> Hi all, the latest version of iFakeLocation now has the ability to enable the hidden Developer Mode toggle without Xcode.

Where is the macOS download?

**Comment by master131** [comment]
> > Hi all, the latest version of iFakeLocation now has the ability to enable the hidden Developer Mode toggle without Xcode.
> 
> Where is the macOS download?

Needed some extra time to package and test it on a Mac first (had to borrow someone else's device) - it's available now.

**Comment by Terminalcreeds** [comment]
im stil having mount problem in the IOS 16 when trying to load the IBSS ,IBEC , Devicetree, ramdisk please can some tell me what to do in this problem?
