### ISSUE TITLE
Ios 13.3 not suppoting

### ISSUE THREAD

**Issue by marknank** [master131/iFakeLocation#9]
My I phone automatically updated to Ios 13.3 and now I fake is not supporting to new update. can you please check?

**Comment by bgktmxg** [comment]
Make a copy of the 13.2 folder inside developer images and rename it to 13.3. It will work straight away

**Comment by marknank** [comment]
> Make a copy of the 13.2 folder inside developer images and rename it to 13.3. It will work straight away

Thank you. Its working now.
