### ISSUE TITLE
Newly updated app does not open on M1 MacOS Monteray

### ISSUE THREAD

**Issue by dionfactor** [master131/iFakeLocation#90]
I installed the new .NET 6.0 Runtime and the new dmg on my Mac running 12.5.1 and the app does not open. The icon bobs up and down once and then doesn't open. I'm running iOS 16 public beta 6, but the same thing happens whether or no the phone is plugged into my computer.

**Comment by master131** [comment]
Can you please confirm if you are using an Intel-based or M1/M2-based Mac? Also can you provide the output of this command from the Terminal:
`dotnet --info`

**Comment by dionfactor** [comment]
M1 Mac, output below (I think)

Last login: Wed Aug 24 09:53:42 on console
Edrolo@Dions-MacBook-Pro ~ % dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
Edrolo@Dions-MacBook-Pro ~ %

**Comment by master131** [comment]
I have only tested it on an Intel based Mac; I don't have an M1/M2 device to personally check - though I suspect it may be because iFakeLocation is built with x64 (Intel) based libraries (but perhaps Rosetta was stepping in to do some translation).

Can you try this in the Terminal and see if there is any output (this assumes you have copied the iFakeLocation application onto your Desktop, adjust the path if required):
`cd ~/Desktop/iFakeLocation.app/bin
dotnet ./iFakeLocation.dll`

**Comment by vrsong** [comment]
I'm having the same problem - M2 MacBook Air on on Monterrey 12.5.1

Here's a screenshot of the error:

https://prnt.sc/8O2jRlJRT9ey

**Comment by dionfactor** [comment]
Same ^^ Damn, i'd love to have this working my Mac :/

**Comment by master131** [comment]
For those with M1/M2 Macs; can you install the .NET **x64** runtime instead (it can co-exist with the ARM64 version and run under emulation using Rosetta):

![image](https://user-images.githubusercontent.com/1592009/186351881-06df5b97-8b8a-4b32-9738-b9205b1a8c32.png)

Then attempt these commands and report if it makes a difference:

```
cd ~/Desktop/iFakeLocation.app/bin
/usr/local/share/dotnet/x64/dotnet ./iFakeLocation.dll
```

**Comment by vrsong** [comment]
Installing the x64 runtime worked to some degree. It launched the page in the browser.

When plugging in my phone and clicking refresh though it gives this error in the browser:


System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.get_OutputStream()
   at iFakeLocation.Program.SetResponse(HttpListenerContext ctx, Object response) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 88
   at iFakeLocation.Program.GetDevices(HttpListenerContext ctx) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 130
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at iFakeLocation.Program.<>c__DisplayClass18_1.<Main>b__5(Object _) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 504



Here's a screenshot of the error

https://prnt.sc/skI_VfUdFZBA

**Comment by master131** [comment]
> Installing the x64 runtime worked to some degree. It launched the page in the browser.
> 
> When plugging in my phone and clicking refresh though, it gives this error in the browser:
> 
> Unable to load shared library 'imobiledevice' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libimobiledevice, 0x0001): tried: 'libimobiledevice' (no such file), '/usr/local/lib/libimobiledevice' (no such file), '/usr/lib/libimobiledevice' (no such file), '/Users/xxx/Desktop/iFakeLocation.app/bin/libimobiledevice' (no such file)
> 
> Here's a screenshot of the error: https://prnt.sc/skI_VfUdFZBA
> 
> Here's what appears in Terminal:
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.HttpListenerResponse'. at System.Net.HttpListenerResponse.CheckDisposed() at System.Net.HttpListenerResponse.get_OutputStream() at iFakeLocation.Program.SetResponse(HttpListenerContext ctx, Object response) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 88 at iFakeLocation.Program.GetDevices(HttpListenerContext ctx) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 130 --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at iFakeLocation.Program.<>c__DisplayClass18_1.
> b__5(Object _) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 504

OK - looks like we're getting somewhere; can you try this:

```
cd ~/Desktop/iFakeLocation.app/bin
export DYLD_LIBRARY_PATH=$PATH:.
/usr/local/share/dotnet/x64/dotnet ./iFakeLocation.dll
```

**Comment by vrsong** [comment]
Woohoo! 

That worked.

**Comment by master131** [comment]
Before I update the releases page; can someone please verify the below works on M1/M2 (I had to ZIP the DMG because Github doesn't let me upload it bare inside an issue):

[ifakelocation-v1.7.0-macosx-x64-rev1.zip](https://github.com/master131/iFakeLocation/files/9415210/ifakelocation-v1.7.0-macosx-x64-rev1.zip)

**Comment by dionfactor** [comment]
Just used that dmg and it works seamlessly, thank you so much!!

**Comment by master131** [comment]
Thanks I've updated the README and Releases page accordingly.

**Comment by vrsong** [comment]
Can confirm that this works.

Thanks for all your work on this!
