### ISSUE TITLE
Compatibility for iOS 16

### ISSUE THREAD

**Issue by tarunbonu** [master131/iFakeLocation#91]
Hi master131,

Please update the application to work for iOS 16. Unfortunately, I am using the beta and cannot use your awesome application. I get an error.
Thank you again for this!

Best!

**Comment by master131** [comment]
Can you explain what error you are getting? It does work with iOS 16; and multiple people have used it successfully. Are you using the latest version - 1.7.0?

**Comment by khell** [comment]
The latest iPadOS 16.1 public beta build isn't supported:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/114870/187088739-e46be981-be47-4aab-9fb3-0435fedfb8ee.png">

**Comment by tarunbonu** [comment]
Hi,

I'm on iOS version 16.0 (20A5356a) and my phone model is iPhone 13 Pro Max.
The error I get is this:

[image: Screen Shot 2022-09-09 at 3.30.24 pm.png]

May be the image for the corresponding iOS version is missing?

**Comment by master131** [comment]
> Hi, I'm on iOS version 16.0 (20A5356a) and my phone model is iPhone 13 Pro Max. The error I get is this: <img width="1287" alt="Screen Shot 2022-09-09 at 3 30 24 pm" src="https://user-images.githubusercontent.com/13234078/189283881-5e42372e-406b-4fc4-99e0-08ba283af6dd.png"> Maybe the image for the corresponding iOS version is missing?

Have you tried restarting your phone?

**Comment by jasondaicoder** [comment]
I am getting different error when using with ios 16

<img width="497" alt="Screen Shot 2022-09-14 at 10 36 13 pm" src="https://user-images.githubusercontent.com/8662103/190155681-05b529d0-e51c-4386-8710-d1329d010e55.png">

It can work by manually toggle the `developer mode` on in the setting, however it looks like that I don't have to do it when looking at the code in [DeviceInformation.cs](https://github.com/master131/iFakeLocation/blob/81ca4437ecb205759ea8015969021625927b25b4/iFakeLocation/DeviceInformation.cs#L257).

**Comment by exit-stage-left** [comment]
consistently getting the following error:
'Please turn on developer mode first via settings >> privacy & security'
I have developer mode on, on my laptop and have restarted phone and laptop several times.
![image](https://user-images.githubusercontent.com/113605256/190402245-17a03e11-3c48-46bf-81d0-8fc0176e74cf.png)

**Comment by master131** [comment]
> I am using iphone 13 with ios16, consistently getting the following error: 'Please turn on developer mode first via settings >> privacy & security' I have developer mode on, on my laptop and have restarted phone and laptop several times. ![image](https://user-images.githubusercontent.com/113605256/190402245-17a03e11-3c48-46bf-81d0-8fc0176e74cf.png) ![image](https://user-images.githubusercontent.com/113605256/190403448-d706fd65-e842-4b68-860e-08b8eed63d37.png)

You need to enable Developer Mode on your iPhone via Settings, not on Windows.

**Comment by master131** [comment]
> I am getting different error when using with ios 16
> 
> <img alt="Screen Shot 2022-09-14 at 10 36 13 pm" width="497" src="https://user-images.githubusercontent.com/8662103/190155681-05b529d0-e51c-4386-8710-d1329d010e55.png">
> 
> It can work by manually toggle the `developer mode` on in the setting, however it looks like that I don't have to do it when looking at the code in [DeviceInformation.cs](https://github.com/master131/iFakeLocation/blob/81ca4437ecb205759ea8015969021625927b25b4/iFakeLocation/DeviceInformation.cs#L257).

Does your device have a passcode enabled?

**Comment by jasondaicoder** [comment]
> Does your device have a passcode enabled?
Yes, it does. However the phone was unlocked before I clicked on `Set Fake Location`.

**Comment by master131** [comment]
> > Does your device have a passcode enabled?
> > Yes, it does. However the phone was unlocked before I clicked on `Set Fake Location`.

I see - I don't know why that error is appearing, but the Developer Mode should be enabled for the app to work correctly regardless.

**Comment by halbesma** [comment]
Since updating to iOS 16 (public release) on my iPhone 12 Pro, I receive the following error:

> Mount failed with status: N/A and error: ImageMountFailed

I then updated to iOS 16.0.2 and updated Apple software on PC, but this didn't solve the issue.

![image](https://user-images.githubusercontent.com/6190089/193411901-f5b3f58c-b5d0-499c-8525-1d71a0bf9f56.png)

**Comment by master131** [comment]
> Since updating to iOS 16 (public release) on my iPhone 12 Pro, I receive the following error:
> 
> > Mount failed with status: N/A and error: ImageMountFailed
> 
> I then updated to iOS 16.0.2 and updated Apple software on PC, then restarted both phone and PC, but this didn't solve the issue.
> 
> ![image](https://user-images.githubusercontent.com/6190089/193411901-f5b3f58c-b5d0-499c-8525-1d71a0bf9f56.png)

Please double check you are using v1.7; you can click on the "About" button to confirm this.

**Comment by halbesma** [comment]
> Please double check you are using v1.7; you can click on the "About" button to confirm this.

Thank you! This sovled the issue.

**Comment by tarunbonu** [comment]
Hi Cameron,

Yes I've tried restarting the phone. I've also tried reinstalling the
application. Is there a way I can clear the files and re-download the image?
Not sure how to get this to work again.

Best,

**Comment by master131** [comment]
> I've updated to iOS16 on my iPhone and I'm trying to update to v1.7 on my MacBook Pro but having issues. I see I need to download a .Net something? Further instructions please?

Install the below for Mac:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.10-macos-x64-installer

**Comment by master131** [comment]
> Hi Cameron, Yes I've tried restarting the phone. I've also tried reinstalling the application. Is there a way I can clear the files and re-download the image? Not sure how to get this to work again

Can you confirm the version of the application through the "About" button - you need to be using v1.7. 

Also, please make sure your phone is unlocked during the process of setting a fake location.
