### ISSUE TITLE
v1.7.0 not working with public iOS16.0 (not beta), Mount failed with status: N/A and error: ImageMountFailed

### ISSUE THREAD

**Issue by s-pankhurst** [master131/iFakeLocation#93]
phone has had trust settings reset and is trusted on W10 PC
device powercycled
unlocked when connected and selected in app
there is no developer mode that I can see to enable in the device OS, commented on by others - see https://www.reddit.com/r/jailbreak/comments/xc8fhv/discussion_the_end_of_jailbreaking_is_near/

previously working OK with iOS15.6

**Comment by master131** [comment]
That thread is irrelevant, it's talking about jailbreaking and not enabling developer mode. Do you have a passcode on your device?

**Comment by s-pankhurst** [comment]
I do, but the phone is unlocked at the time.  I've also just tried unlocking with both face recognition and passcode and get the same error.

**Comment by master131** [comment]
> I do, but the phone is unlocked at the time. I've also just tried unlocking with both face recognition and passcode and get the same error.
> 
> I was specifically referring to this comment, if it is in relation to something different then my apologies. https://www.reddit.com/r/jailbreak/comments/xc8fhv/discussion_the_end_of_jailbreaking_is_near/io756fb/

Developer mode still exists in the iOS 16 official release, I have confirmed it myself today. Have you tried restarting your phone?

**Comment by s-pankhurst** [comment]
restarted twice before I raised the issue, and just done again.  developer mode is simply not there any more, see the attached screen shot.  have now verified this on two phones upgraded to iOS16, and also one that was upgraded to iOS15.7.

note this is the public release of iOS16, it's only been out less than 48 hours.  this is not the beta.  https://www.apple.com/newsroom/2022/09/ios-16-is-available-today/

![Screenshot 2022-09-14 at 7 11 36 pm](https://user-images.githubusercontent.com/113505139/190115435-530f5312-44f6-437b-b99d-42671ea06503.png)

**Comment by master131** [comment]
Unfortunately I cannot replicate the issue; I have tested on an iPhone 12 running the official iOS 16 release (updated < 2 hours ago) and was prompted to enable Developer Mode after attempt to set a location in iFakeLocation (this is important because the option isn't visible until iFakeLocation does some magic to make it appear).

**Comment by s-pankhurst** [comment]
OK, I'm wondering if this is either possibly a bad download or unpack of the zip.  I again downloaded v1.7.0 and unpacked it to a local folder and now it prompted to enable developer mode/reboot on one phone as expected.

also just updated another phone to iOS16 and got the same thing.  don't want to screw too much with the other phones are they are work phones and IT departments get tetchy.

so ultimately it works as expected... unpacked the archive in the same way both times, so no idea what caused it to be an issue the first time around!

thanks for your help.
