### ISSUE TITLE
Your device's iOS version is not supported at this time (15.7)

### ISSUE THREAD

**Issue by javafun** [master131/iFakeLocation#94]
Can you provide fix for this please?

Thanks

**Comment by ozblogger** [comment]
Go to developer image folder
Rename 15.6 to 15.7
And try again
Worked for me

**Comment by master131** [comment]
I've updated support for iOS 15.7; and also updated the image for iOS 15.6 from the latest version of Xcode - can you check now?

**Comment by javafun** [comment]
Thanks, however it is still not working and receive the following error

<img width="494" alt="2022-09-19_17-31-23" src="https://user-images.githubusercontent.com/332991/190969344-91981336-e7c0-4523-ae3f-cfc2a63970e9.png">

**Comment by vyan024** [comment]
I just noticed version 15.7 links to 15.6 zip file. Is that correct?

![image](https://user-images.githubusercontent.com/54790930/190974123-432c46d7-8665-4f72-8a01-452e8b928723.png)

**Comment by master131** [comment]
Apple hasn't provided any specific developer image for iOS 15.7 that I am aware of; usually when they don't provide one, the previous iOS version works - I'm checking again just incase.

**Comment by master131** [comment]
After a bit of searching, it seems that the image provided in Xcode 14 (the latest version of Xcode by Apple) does not have the right images for iOS 15.7 and that it must be obtained from an older version:
https://github.com/filsv/iOSDeviceSupport/issues/144

I have updated the images in update.json accordingly; can you delete the DeveloperImages folder (or re-download iFakeLocation) and see if it's working now.

**Comment by javafun** [comment]
I just tested and it seems working like a charm. Thanks
