### ISSUE TITLE
Not Working Iphone 14 Pro Max IOS. 16

### ISSUE THREAD

**Issue by lakshey97** [master131/iFakeLocation#95]
Its not working with on Iphone 14 Pro Max with IOS 16 please help
<img width="693" alt="Screen Shot 2022-09-17 at 11 28 25 am" src="https://user-images.githubusercontent.com/98377432/190835231-99ce85a2-a22a-4e1b-b9de-a6d6fa66593c.png">

**Comment by master131** [comment]
- Confirm that you are using iFakelocation v1.7.0, the older versions do not work with iOS 16.
- Try to restarting your iPhone if you haven't already. 
- When you tried to set a location in iFakeLocation, it should have prompted you to enable Developer Mode on your iPhone, did you do this?

![image](https://user-images.githubusercontent.com/1592009/190839080-728aad25-cf4a-41f1-9184-ee029880183d.png)

![](https://camo.githubusercontent.com/7805d001e315e4c2f6f561d4090d5b913f0ec693d22338be4b5bbac7b051a902/68747470733a2f2f646f63732d6173736574732e646576656c6f7065722e6170706c652e636f6d2f7075626c69736865642f34343931616262643032623162393461623630306330383731373766636636642f646576656c6f7065722d6d6f64652d30334032782e706e67)

**Comment by Lamchop1** [comment]
Im having issue with this too but with an iPhone 12 iOS 16 and currently using v1.7.0 of iFL. everything is running as it should but it wont prompt my phone to download anything for it to get into developer mode, please help
