### ISSUE TITLE
Issues with using on IOS 15.7

### ISSUE THREAD

**Issue by John7421** [master131/iFakeLocation#96]
Hi,

Used Ifakelocation on IOS 15.6.1 successfully in the past and have now upgraded to IOS 15.7.
Using the latest Ifakelocation v1.7 on Win 11 x64, I'm unable to set a fake location and get the following error "Mount failed with status: N/A and error: ImageMountFailed". Itunes and Icloud on Windows works, the Device shows up in the device names, but does not want to set the fake location.

Have restarted the iphone a couple of times and tried another pc (Win 10 x64), however without success. Another iphone on IOs 15.6.1 still works great with both pc's.

Any Ideas what I should do or test?

**Comment by master131** [comment]
I have updated the images in update.json accordingly; can you delete the DeveloperImages folder (or re-download iFakeLocation) and see if it's working now.

**Comment by John7421** [comment]
Thanks master131, perfect, deleted the images and it does work now.
Thanks for your support!
