### ISSUE TITLE
Mount failed with status: N/A and error: ImageMountFailed

### ISSUE THREAD

**Issue by gg123987** [master131/iFakeLocation#98]
hello
i encountered this issue this morning...
Mount failed with status: N/A and error: ImageMountFailed
i am using windows 11 and iphone X
i have been doing this for a while now and it has been working fine until now...not sure what the issue is...
thanks so much!

**Comment by master131** [comment]
Basic checklist:
- Are you using the latest version of iFakeLocation - currently that is v1.7.0
- Is your phone unlocked when you are setting the fake location?
- Have you tried to restart your phone?

**Comment by gg123987** [comment]
i am using version 1.6
my phone is unlocked
i have tried restarting my phone
